# Generated by Django 4.2.7 on 2023-11-29 02:43
from django.contrib.auth.management import create_permissions
from django.contrib.auth.models import Group, Permission
from django.db import migrations, transaction
from django.contrib import admin
from django.contrib.auth.admin import GroupAdmin


def add_groups(apps, _):
	# need to create the default permissions here since otherwise they don't exist yet
	for app_config in apps.get_app_configs():
		app_config.models_module = True
		create_permissions(app_config, verbosity=0)
		app_config.models_module = None

	ta_perms = ["edit_own_user_data", "view_ta_section_assignments", "view_public_user_data"]
	instructor_perms = ta_perms + ["view_own_course_assignments", "notify_own_tas", "assign_own_tas_to_section"]
	supervisor_perms = instructor_perms + ["create_course", "create_section", "view_all_course_data",
											"view_all_section_data", "create_user", "delete_user", "view_all_user_data",
											"edit_all_user_data", "notify_all_users", "assign_all_instructors",
											"assign_all_tas_to_course", "assign_all_tas_to_section"]

	with transaction.atomic():
		supervisor = Group.objects.get_or_create(name="Supervisor")[0]
		supervisor.permissions.add(*[Permission.objects.get(codename=p) for p in supervisor_perms])
		instructor = Group.objects.get_or_create(name="Instructor")[0]
		instructor.permissions.add(*[Permission.objects.get(codename=p) for p in instructor_perms])
		ta = Group.objects.get_or_create(name="TA")[0]
		ta.permissions.add(*[Permission.objects.get(codename=p) for p in ta_perms])

	admin.site.register((supervisor, instructor, ta), GroupAdmin)


class Migration(migrations.Migration):
	dependencies = [
		('ta_manager', '0001_initial'),
	]

	operations = [
		migrations.RunPython(add_groups)
	]
